<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.TagHelpers" Version="2.3.13" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.0" />
    <PackageReference Include="UoN.ExpressiveAnnotations.NetCore" Version="1.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Clinck.Domain\Clinck.Domain.csproj" />
  </ItemGroup>

</Project>
